/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'rounded-2xl',
    'rounded-t-2xl',
    'rounded-xl',
    'shadow-xl',
    'border',
    'border-gray-200',
    'px-5',
    'py-3',
    'py-4',
    'px-4',
    'bg-white',
    'bg-gray-100',
    'text-base',
    'text-white',
    'text-gray-900',
    'text-gray-400',
    'flex',
    'flex-col',
    'flex-1',
    'overflow-y-auto',
    'space-y-4',
    'items-center',
    'justify-between',
    'justify-end',
    'justify-start',
    'max-w-[85%]',
    'leading-relaxed',
    'transition-colors',
    'focus:outline-none',
    'focus:border-blue-500',
    'bg-blue-600',
    'bg-gray-100',
    'text-gray-800',
    'text-xs',
    'text-base',
    'text-lg',
    'text-sm',
    'p-3',
    'p-2',
    'p-2.5',
    'gap-2',
    'w-5',
    'h-5',
    'select-none',
    'mb-2',
    'pb-2',
    'pt-1',
    'ml-2',
    'rounded-t-lg',
    'rounded-lg',
    'rounded-full',
    'shadow',
    'shadow-sm',
    'shadow-lg',
    'bg-transparent',
    'hover:opacity-75',
    'hover:underline',
    'focus:ring-2',
    'focus:ring-white/50',
    'transition-all',
    'duration-300',
    'z-50',
    'fixed',
    'bottom-5',
    'right-5',
  ],
  theme: {
    extend: {
      animation: {
        'bounce-delayed': 'bounce 1s infinite 0.5s',
      },
      zIndex: {
        '100': '100',
      },
    },
  },
  plugins: [],
} 